{
 "title": "GPU Server Status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   }
  ]
 },
 "panels": [
  { "title": "Quick view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT median(\"usage_user\") FROM \"cpu\" WHERE (\"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_system\") FROM \"cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_user\") FROM \"cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "iowait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_iowait\") FROM \"cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_idle\") FROM \"cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Total, GB",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Used, GB",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "Shared, GB",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "shared" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "Mapped, GB",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "mapped" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GPU Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT median(\"utilization_gpu\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "utilization_gpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name $tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT last(\"utilization_gpu\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($interval), \"index\", \"name\" fill(null)\n",
     "select": [
      [
       { "params": [ "utilization_gpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU RAM",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "Total $tag_name $tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT last(\"memory_total\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval), \"index\", \"name\" fill(null)\n",
     "select": [
      [
       { "params": [ "memory_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Used $tag_name $tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT median(\"memory_used\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval), \"index\", \"name\" fill(null)\n",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "query": "SELECT median(\"temp_input\") FROM \"sensors\" WHERE (\"chip\" = 'coretemp-isa-0000' AND \"feature\" = 'package_id_0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "package_id_0" }
     ]
    },
    {
     "alias": "CPU 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "query": "SELECT median(\"temp_input\") FROM \"sensors\" WHERE (\"chip\" = 'coretemp-isa-0001' AND \"feature\" = 'package_id_1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "package_id_0" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CPU 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "query": "SELECT median(\"temp_input\") FROM \"sensors\" WHERE (\"chip\" = 'coretemp-isa-0000' AND \"feature\" = 'package_id_0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "package_id_0" }
     ]
    },
    {
     "alias": "CPU 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "query": "SELECT median(\"temp_input\") FROM \"sensors\" WHERE (\"chip\" = 'coretemp-isa-0001' AND \"feature\" = 'package_id_1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "package_id_0" }
     ]
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT max(\"temperature_gpu\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature_gpu" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_name $tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT last(\"temperature_gpu\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($interval), \"index\", \"name\" fill(null)\n",
     "select": [
      [
       { "params": [ "temperature_gpu" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Frequency",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Graphics $tag_name $tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT last(\"clocks_current_graphics\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval), \"index\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "clocks_current_graphics" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Mem  $tag_name $tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT last(\"clocks_current_memory\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval), \"index\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "clocks_current_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "SM $tag_name $tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT last(\"clocks_current_sm\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval), \"index\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "clocks_current_sm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Video $tag_name $tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT last(\"clocks_current_video\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval), \"index\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "clocks_current_video" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Xilinx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "FPGA Temp",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_xilinx_xbutil",
     "query": "SELECT last(\"memory_used\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "physical_thermal_fpga_temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Platform temperature",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"physical_thermal_fpga_temp\") AS \"fpga_temp\", last(\"physical_thermal_pcb_btm_front\") AS \"pcb_btm_front\", last(\"physical_thermal_pcb_top_front\") AS \"pcb_top_front\", last(\"physical_thermal_pcb_top_rear\") AS \"pcb_top_rear\", last(\"physical_thermal_vccint_temp\") AS \"vccint\" FROM \"exec_xilinx_xbutil\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "FAN and Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Fan 1 RPM",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "rpm" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "fan1" }
     ]
    }
   ]
  },
  {
   "title": "Fan 2 RPM",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "rpm" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "fan2" }
     ]
    }
   ]
  },
  {
   "title": "Fan A RPM",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "rpm" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "fana" }
     ]
    }
   ]
  },
  {
   "title": "Platform RPM",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT last(\"value\") FROM \"ipmi_sensor\" WHERE (\"unit\" = 'rpm' AND \"name\" =~ /fan[a-z0-9].*/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "rpm" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "fana" }
     ]
    }
   ]
  },
  {
   "title": "Platform temperature",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT last(\"value\") FROM \"ipmi_sensor\" WHERE (\"unit\" = 'degrees_c') AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "rpm" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "fana" }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Cores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"cpu\" =~ /cpu[0-9].*/) AND $timeFilter GROUP BY time($interval), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_process_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "query": "SELECT mean(\"cpu_usage\") FROM \"procstat\" WHERE $timeFilter GROUP BY time($__interval), \"process_name\"",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "repeat": "core_per_cpu",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"cpu\" =~ /cpu[0-9].*/) AND $timeFilter GROUP BY time($interval) , \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temp graph",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CPU 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "query": "SELECT median(\"temp_input\") FROM \"sensors\" WHERE (\"chip\" = 'coretemp-isa-0000' AND \"feature\" = 'package_id_0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "package_id_0" }
     ]
    },
    {
     "alias": "CPU 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "query": "SELECT median(\"temp_input\") FROM \"sensors\" WHERE (\"chip\" = 'coretemp-isa-0001' AND \"feature\" = 'package_id_1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=", "value": "coretemp-isa-0000" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "package_id_0" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM Used %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Ram Used, GB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Total, GB",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Used, GB",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ]
      },
      {
       "alias": "Shared, GB",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "shared" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ]
      },
      {
       "alias": "Mapped, GB",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "mapped" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temp graph",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nvidia_smi",
       "query": "SELECT last(\"memory_used\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "temperature_gpu" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GPU Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 11, "y": 10 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nvidia_smi",
       "query": "SELECT last(\"memory_used\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "memory_used" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ]
      },
      {
       "alias": "Total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nvidia_smi",
       "query": "SELECT last(\"memory_used\") FROM \"nvidia_smi\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "memory_total" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}